on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

name: PR Checker

jobs:

  build:
    name: Build, Test, Coverage
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Go 1.16.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Download Dependencies
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go mod download

      - name: Test Coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: c2de998a65e4a6d9bd0739d4313d83c37d585a89c70eea43781fcfbefc6a6e0c
        with:
          coverageCommand: go test -coverprofile c.out -v ./... -run="^Test"
          coverageLocations: ${{github.workspace}}/c.out:gocov
          prefix: github.com/hazelcast/hazelcast-cloud-sdk-go
